@startuml
start
:User executes facilitator find command;
:Parser parses keywords;
if () then ([keyword is not empty])
    :Logic executes command;
    :Model updates filtered facilitator list;
    :Ui shows the updated facilitator list;
else ([else])
    :Ui shows error message;
endif
stop
@enduml
