@startuml
start
:User executes class delete command;
:Parser parses index;
if () then ([index is valid])
    :Logic executes command;
    if () then ([index is not out of bound and module code is present and valid])
        :Model deletes lesson from LessonList;
        :Logic saves LessonList to Storage;
        :Ui shows the list of lessons for that module;
    else ([else])
        :Ui shows error message;
    endif
else ([else])
    :Ui shows error message;
endif
stop
@enduml
