@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Module {
}

Package Facilitator {
}

Package Lesson {
}

Package Task {
}

Package Calendar {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueModuleList
AddressBook *--> "1" UniqueFacilitatorList
AddressBook *--> "1" UniqueTaskList
AddressBook *--> "1" LessonList

ModelManager -->"1" Calendar
ModelManager -->"1" Module : filtered list
ModelManager -->"1" Facilitator : filtered list
ModelManager -->"1" Task : filtered list
ModelManager -->"1" Lesson : filtered list
@enduml
