@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam ArrowFontSize 15

Package Model <<Rectangle>>{
Interface ReadOnlyModManager <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class ModManager
Class ReadOnlyModManager
Class Model
Class ModelManager
Class UserPrefs
Interface ReadOnlyUserPrefs <<Interface>>
Class DoableActionList
Package Module {
}

Package Facilitator {
}

Package Lesson {
}

Package Task {
}

Package Calendar {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModManager .up.|> ReadOnlyModManager

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" ModManager
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ModManager *--> "1" UniqueModuleList
ModManager *--> "1" UniqueFacilitatorList
ModManager *--> "1" UniqueTaskList
ModManager *--> "1" LessonList

ModelManager *-> "1" DoableActionList
ModelManager -->"1" Calendar
ModelManager -->"*" Module
ModelManager -->"*" Facilitator : filtered list
ModelManager -->"*" Task : filtered list
ModelManager -->"*" Lesson : filtered list
@enduml
