@startuml
start
:User executes module view command;
if () then ([index or module code provided])
    if () then ([index is provided])
        :Parser parses index;
        if () then ([index is valid])
            :Logic executes command;
            if () then ([index is not out of bounds])
                :Model updates module viewed;
                :Model updates facilitator list for module;
                :Model updates task list for module;
            else ([else])
            endif
        else ([else])
        endif
    else ([module code is provided])
        :Parser parses module code;
        if () then ([module code is valid])
            :Logic executes command;
            if () then ([module exists in ModManager])
                :Model updates module viewed;
                :Model updates facilitator list for module;
                :Model updates task list for module;
            else ([else])
            endif
        else ([else])
        endif
    endif
else ([else])
endif
stop
@enduml
