@startuml
start
:User executes module view command;
if () then ([index or module code provided])
    if () then ([index is provided])
        :Parser parses index;
        if () then ([index is valid])
            :Logic executes command;
            if () then ([index is not out of bounds])
                :Model updates module viewed;
                :Model updates facilitator list for module;
                :Model updates task list for module;
                :Ui shows classes, tasks and facilitators for module;
            else ([else])
                :Ui shows error message;
            endif
        else ([else])
            :Ui shows error message;
        endif
    else ([module code is provided])
        :Parser parses module code;
        if () then ([module code is valid])
            :Logic executes command;
            if () then ([module exists in ModManager])
                :Model updates module viewed;
                :Model updates facilitator list for module;
                :Model updates task list for module;
                :Ui shows classes, tasks and facilitators for module;
            else ([else])
                :Ui shows error message;
            endif
        else ([else])
            :Ui shows error message;
        endif
    endif
else ([else])
    :Ui shows error message;
endif
stop
@enduml
