@startuml
start
:User executes module delete command;
if () then ([index or module code is provided])
    if () then ([index is provided])
        :Parser parses index;
        if () then ([index is valid])
            :Logic executes command;
            if () then ([index is not out of bounds])
                :Model deletes module from UniqueModuleList;
                :Model deletes facilitators of the module
                from UniqueFacilitatorList in ModManager;
                :Model deletes tasks of the module
                from UniqueTaskList in ModManager;
                :Model delete lessons of the module
                from LessonList in ModManager;
                :Logic saves ModManager to Storage;
                :Ui shows the updated module list;
            else ([else])
                :Ui shows error message;
            endif
        else ([else])
            :Ui shows error message;
        endif
    else ([module code is provided])
        :Parser parses module code;
        if () then ([module code is valid])
            :Logic executes command;
            if () then ([module exists in ModManager])
                :Model deletes module from UniqueModuleList;
                :Model deletes facilitators of the module
                from UniqueFacilitatorList in ModManager;
                :Model deletes tasks of the module
                from UniqueTaskList in ModManager;
                :Model delete lessons of the module
                from LessonList in ModManager;
                :Logic saves ModManager to Storage;
                :Ui shows the updated module list;
            else ([else])
                :Ui shows error message;
            endif
        else ([else])
            :Ui shows error message;
        endif
    endif
else ([else])
    :Ui shows error message;
endif
stop
@enduml
