@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class StatusBarFooter
Class CommandBox

package CalendarUI {}
package FacilitatorUI {}
package LessonUI {}
package ModuleUI {}
package TaskUI {}

}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -right-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> StatusBarFooter
MainWindow *-right-> CalendarUI
MainWindow *-right-> FacilitatorUI
MainWindow *-right-> LessonUI
MainWindow *-right-> ModuleUI
MainWindow *-right-> TaskUI

MainWindow -left-|> UiPart

ResultDisplay -down--|> UiPart
CommandBox -down--|> UiPart
StatusBarFooter -down--|> UiPart
HelpWindow -down---|> UiPart
CalendarUI -down---|> UiPart
FacilitatorUI -down---|> UiPart
LessonUI -down---|> UiPart
ModuleUI -down---|> UiPart
TaskUI -down---|> UiPart

UiManager --up-> Logic
MainWindow --up-> Logic

CalendarUI ...> Model
FacilitatorUI ...> Model
LessonUI ...> Model
ModuleUI ...> Model
TaskUI ...> Model

HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
