= Nguyen Dang Phuc Nhat - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets
:experimental:

== PROJECT: Mod Manager


== Overview
This portfolio summarizes my contribution to Mod Manager, a software developed by a team of me and 4 other fellow CS2103T students.
Over a period of 8 weeks, we have managed to morph https://github.com/nus-cs2103-AY1920S2/addressbook-level3[Address Book Level 3 (AB3)]
into a CLI application that aims to assist students with managing information related to the modules they're taking -
classes, tasks, and facilitators. Mod Manager takes commands from users through a Command Line Interface (CLI), and displays
information with a Graphic User Interface (GUI). It is written in Java, and has about 25 kLoc.

Below are my contributions to the project.

== Summary of contributions

*Major enhancements*:

* Added the ability to undo/redo previous commands
** What it does:
*** Allows the user to undo previous commands that caused changes to the database.
*** Allows the user to reverse previous undo commands via the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects almost all existing commands and any commands implemented in the future.
Despite the challenge of having to understand the entire system, its implementation has been kept to be as convenient as possible, i.e.
requiring very minor changes to other commands. A pattern has been constructed to help future commands integrate well with this enhancement.

* Added the Task ID number system
** What it does:
*** Allows the user to manage tasks across all modules without relying on visible lists.
** Justification: Without a Task ID number, the user must always view the list of tasks before doing anything with a particular task.
With this enhancement, a user can edit, delete, or mark as done a task anytime as long as they know its ID number.
** Highlights: This enhancement imposes a visible constraint on the maximum number of tasks for each module, which can be helpful to
understanding the system. There could have been many ways to implement the enhancement, but the current one was chosen due to its
simpler nature and being easy to upgrade in the future.


*Minor enhancements*:

* Added an internal command history that allows the user to navigate to previous commands using up/down keys.
* Re-designed the calendar UI to the current version.
* Added the ability to edit/delete modules, facilitators and tasks using module codes, facilitator names and task ID numbers respectively.
* Refactored AB3 parser code to provide better abstraction, and be a pattern for other commands' implementations.

*Code contributed*:

* [https://github.com/AY1920S2-CS2103T-F10-4/main/pulls?q=is%3Apr+author%3ANNpanpan+is%3Aclosed+[Functional code]][https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=NNpanpan&sort=totalCommits%20dsc&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Reposense]]

*Other contributions*:

** Project management:
*** Reviewed and merged pull requests on Github.
** Documentation:
*** Wrote the task edit/delete, and part of general features sections of the User Guide: https://github.com/AY1920S2-CS2103T-F10-4/main/pull/135[#135], https://github.com/AY1920S2-CS2103T-F10-4/main/pull/196[#196]
*** Wrote the general features and task edit/delete sections of the Developer Guide: https://github.com/AY1920S2-CS2103T-F10-4/main/pull/196[#196]
** Community:
*** PR reviews (with non-trivial comments): https://github.com/AY1920S2-CS2103T-F10-4/main/pull/189[#189]
*** Reformatted .puml settings for the team: https://github.com/AY1920S2-CS2103T-F10-4/main/pull/109[#109]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===
== Task feature
include::../UserGuide.adoc[tag=task-edit-delete]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
=== Model Component
include::../DeveloperGuide.adoc[tag=doable-package]

=== General Features
include::../DeveloperGuide.adoc[tag=general-features]

=== Task Management Feature
include::../DeveloperGuide.adoc[tag=task-edit]


